---
name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'test'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('./Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: test
        run: |
          rspec
